# H2? "??"? ?? ? ?? ?? ??? ?? (data ??? ???)
spring.datasource.url=jdbc:h2:file:./data/wishdb
spring.datasource.username=sa
spring.datasource.password=

# ?????? DB ??? ? ? ?? H2 ?? ??
spring.h2.console.enabled=true

# ???? ?? ??? ?? ??/??
spring.jpa.hibernate.ddl-auto=update
# ???? SQL? ??? ?? (??? ? ?? ??? ??)
spring.jpa.show-sql=true
spring.jpa.open-in-view=false